#release configuration
#Mon Jun 12 14:10:38 CST 2023
project.scm.org.apache.rocketmq\:rocketmq-openmessaging.empty=true
completedPhase=end-release
project.dev.org.apache.rocketmq\:rocketmq-proxy=5.1.3-SNAPSHOT
project.dev.org.apache.rocketmq\:rocketmq-remoting=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-tiered-store.empty=true
exec.additionalArguments=-Papache-release -DskipTests -Dspotbugs.skip\=true -P alibaba,signed_release
exec.snapshotReleasePluginAllowed=false
project.dev.org.apache.rocketmq\:rocketmq-srvutil=5.1.3-SNAPSHOT
project.dev.org.apache.rocketmq\:rocketmq-store=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-broker=5.1.2
project.rel.org.apache.rocketmq\:rocketmq-tools=5.1.2
project.rel.org.apache.rocketmq\:rocketmq-controller=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-controller=5.1.3-SNAPSHOT
scm.tag=rocketmq-all-5.1.2
project.scm.org.apache.rocketmq\:rocketmq-srvutil.empty=true
project.scm.org.apache.rocketmq\:rocketmq-remoting.empty=true
project.scm.org.apache.rocketmq\:rocketmq-all.tag=HEAD
project.scm.org.apache.rocketmq\:rocketmq-all.connection=scm\:git\:git@github.com\:apache/rocketmq.git
project.dev.org.apache.rocketmq\:rocketmq-tiered-store=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-common=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-broker=5.1.3-SNAPSHOT
project.dev.org.apache.rocketmq\:rocketmq-acl=5.1.3-SNAPSHOT
project.dev.org.apache.rocketmq\:rocketmq-example=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-test=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-openmessaging=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-example.empty=true
project.rel.org.apache.rocketmq\:rocketmq-remoting=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-common=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-distribution=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-all=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-proxy.empty=true
project.dev.org.apache.rocketmq\:rocketmq-container=5.1.3-SNAPSHOT
project.dev.org.apache.rocketmq\:rocketmq-namesrv=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-common.empty=true
project.scm.org.apache.rocketmq\:rocketmq-filter.empty=true
project.scm.org.apache.rocketmq\:rocketmq-container.empty=true
project.scm.org.apache.rocketmq\:rocketmq-distribution.empty=true
project.rel.org.apache.rocketmq\:rocketmq-filter=5.1.2
remoteTagging=true
scm.url=scm\:git\:git@github.com\:apache/rocketmq.git
project.scm.org.apache.rocketmq\:rocketmq-all.url=git@github.com\:apache/rocketmq.git
scm.commentPrefix=[maven-release-plugin] 
project.dev.org.apache.rocketmq\:rocketmq-filter=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-tools.empty=true
project.rel.org.apache.rocketmq\:rocketmq-proxy=5.1.2
project.scm.org.apache.rocketmq\:rocketmq-store.empty=true
project.scm.org.apache.rocketmq\:rocketmq-all.developerConnection=scm\:git\:git@github.com\:apache/rocketmq.git
project.rel.org.apache.rocketmq\:rocketmq-acl=5.1.2
project.scm.org.apache.rocketmq\:rocketmq-namesrv.empty=true
project.rel.org.apache.rocketmq\:rocketmq-client=5.1.2
project.rel.org.apache.rocketmq\:rocketmq-all=5.1.2
pushChanges=true
project.dev.org.apache.rocketmq\:rocketmq-tools=5.1.3-SNAPSHOT
project.scm.org.apache.rocketmq\:rocketmq-acl.empty=true
project.dev.org.apache.rocketmq\:rocketmq-client=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-srvutil=5.1.2
project.rel.org.apache.rocketmq\:rocketmq-store=5.1.2
projectVersionPolicyId=default
project.scm.org.apache.rocketmq\:rocketmq-test.empty=true
project.scm.org.apache.rocketmq\:rocketmq-client.empty=true
project.dev.org.apache.rocketmq\:rocketmq-distribution=5.1.3-SNAPSHOT
preparationGoals=clean verify
project.rel.org.apache.rocketmq\:rocketmq-tiered-store=5.1.2
project.rel.org.apache.rocketmq\:rocketmq-example=5.1.2
project.scm.org.apache.rocketmq\:rocketmq-controller.empty=true
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.rel.org.apache.rocketmq\:rocketmq-container=5.1.2
project.dev.org.apache.rocketmq\:rocketmq-test=5.1.3-SNAPSHOT
project.rel.org.apache.rocketmq\:rocketmq-namesrv=5.1.2
project.scm.org.apache.rocketmq\:rocketmq-broker.empty=true
project.rel.org.apache.rocketmq\:rocketmq-openmessaging=5.1.2
